In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
#from  import g_key

API KEY FROM GITIGNORE

In [19]:
#Load the csv exported in Part I to a DataFrame

#Read CSV File
output_file = "../WeatherPy/output_data/City_Data.csv"
weather = pd.read_csv(output_file)
weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Mporokoso,-9.37,30.12,288.35,84.0,73.0,2.94,ZM,1.588997e+09
1,Saskylakh,71.92,114.08,258.03,93.0,59.0,2.14,RU,0.000000e+00
2,Juradó,7.11,-77.76,300.52,85.0,100.0,1.47,CO,1.588935e+09
3,Sitka,57.05,-135.33,288.15,47.0,90.0,2.10,US,1.588943e+09
4,Bethel,41.37,-73.41,279.26,93.0,90.0,3.89,US,1.588931e+09
...,...,...,...,...,...,...,...,...,...
566,Fare,-16.70,-151.02,301.23,76.0,97.0,5.29,PF,1.588955e+09
567,Lumut,4.23,100.63,300.15,94.0,20.0,1.00,MY,1.588979e+09
568,Kirensk,57.79,108.11,277.84,59.0,1.0,0.50,RU,1.588970e+09
569,Nanga Eboko,4.68,12.37,294.38,97.0,87.0,0.72,CM,1.589000e+09
570,Hurghada,27.26,33.81,297.15,27.0,0.0,6.26,EG,1.588993e+09

In [31]:
#Humidity Heatmap

gmaps.configure(api_key = "AIzaSyAJZlKxLzXtkN8obJKH1cTM--S96ZrbY94")
locations = weather[["Lat", "Lng"]]
hum = weather["Humidity"]

#Plot Gmaps
fig = gmaps.figure()

#Create a heat layer
#heat_layer=gmaps.heatmap_layer(locations,
#weights = hum, dissipating = False, max_intensity = 100, point_radius=1)
#fig.add_layer(gmaps.heatmap_layer(locations, weights = hum))
#fig.add_layer(gmaps.heatmap_layer(locations, weights = hum))
#fig

In [26]:
locations

       Lat     Lng
0    -9.37   30.12
1    71.92  114.08
2     7.11  -77.76
3    57.05 -135.33
4    41.37  -73.41
..     ...     ...
566 -16.70 -151.02
567   4.23  100.63
568  57.79  108.11
569   4.68   12.37
570  27.26   33.81

[571 rows x 2 columns]

In [32]:
heatmap = gmaps.heatmap_layer(locations, max_intensity=100)